import { allRatings, arr, has, listText, ratedAs, real, str, asBudget } from './helpers';
import type { Answers, Level, Question, SectionId } from './types';
import { AGE_OPTS, BREASTFEEDING, EATING_DISORDER, noWeightLoss, PREGNANT, REFER_NOTE } from '../profile/screen';

export const SECTIONS: { id: SectionId; name: string; intro: string }[] = [
  { id: 'safety', name: 'Safety', intro: 'First, the non-negotiables. These keep you safe, so I treat them differently from likes and dislikes.' },
  { id: 'goals', name: 'Goals', intro: 'Now, what we are working toward. No weigh-ins needed.' },
  { id: 'taste', name: 'Taste', intro: 'Let’s figure out what you actually enjoy eating.' },
  { id: 'picky', name: 'Textures', intro: 'Now the details that make or break a meal for you.' },
  { id: 'sweets', name: 'Sweets', intro: 'You can absolutely keep something sweet in the plan. Let’s make it work for you.' },
  { id: 'prep', name: 'Prep day', intro: 'Let’s plan the one day you cook.' },
  { id: 'life', name: 'Practical', intro: 'Last few practical things, then I’ll show you what I learned.' },
];

export const LEVELS: { id: Level; label: string; name: string }[] = [
  { id: 'love', label: 'Love', name: 'Love it' },
  { id: 'like', label: 'Like', name: 'Like it' },
  { id: 'okay', label: 'Okay', name: 'It’s okay' },
  { id: 'ways', label: 'Some ways', name: 'Only certain ways' },
  { id: 'dislike', label: 'Dislike', name: 'Dislike it' },
  { id: 'never', label: 'Never', name: 'Never suggest' },
];

export const FOODS: Record<string, { n: string; e: string; veg?: boolean }> = {
  chicken: { n: 'Chicken', e: '🍗' }, beef: { n: 'Ground beef', e: '🥩' }, turkey: { n: 'Turkey', e: '🦃' },
  salmon: { n: 'Salmon', e: '🐟' }, tuna: { n: 'Tuna', e: '🥫' }, eggs: { n: 'Eggs', e: '🥚' }, tofu: { n: 'Tofu', e: '⬜' }, beans: { n: 'Beans', e: '🫘' },
  rice: { n: 'Rice', e: '🍚' }, pasta: { n: 'Pasta', e: '🍝' }, potatoes: { n: 'Potatoes', e: '🥔' }, oats: { n: 'Oats', e: '🥣' },
  cheese: { n: 'Cheese', e: '🧀' }, yogurt: { n: 'Greek yogurt', e: '🥛' },
  broccoli: { n: 'Broccoli', e: '🥦', veg: true }, carrots: { n: 'Carrots', e: '🥕', veg: true },
  spinach: { n: 'Spinach', e: '🥬', veg: true }, peppers: { n: 'Bell peppers', e: '🫑', veg: true },
  zucchini: { n: 'Zucchini', e: '🥒', veg: true }, tomatoes: { n: 'Tomatoes', e: '🍅', veg: true },
  onions: { n: 'Onions', e: '🧅', veg: true }, mushrooms: { n: 'Mushrooms', e: '🍄', veg: true },
  greenbeans: { n: 'Green beans', e: '🫛', veg: true }, corn: { n: 'Corn', e: '🌽', veg: true }, avocado: { n: 'Avocado', e: '🥑' },
  berries: { n: 'Berries', e: '🍓' }, bananas: { n: 'Bananas', e: '🍌' }, apples: { n: 'Apples', e: '🍎' }, grapes: { n: 'Grapes', e: '🍇' },
};
export const FOOD_GROUP_A = ['chicken', 'beef', 'turkey', 'salmon', 'tuna', 'eggs', 'tofu', 'beans', 'rice', 'pasta', 'potatoes', 'oats', 'cheese', 'yogurt'];
export const FOOD_GROUP_B = ['broccoli', 'carrots', 'spinach', 'peppers', 'zucchini', 'tomatoes', 'onions', 'mushrooms', 'greenbeans', 'corn', 'avocado', 'berries', 'bananas', 'apples', 'grapes'];
export const WAYS = ['Roasted until crispy', 'Air-fried', 'Blended into a sauce', 'Finely chopped, cooked soft', 'Mashed', 'Baked into something', 'With cheese', 'Raw', 'Steamed', 'Scrambled', 'Hard-boiled', 'Fried', 'Sweetened or flavored'];

export const ALLERGY_OPTS = ['Peanuts', 'Tree nuts', 'Milk / dairy', 'Eggs', 'Wheat / gluten', 'Soy', 'Fish', 'Shellfish', 'Sesame'];
export const CURRENCIES = ['USD', 'CAD', 'EUR', 'GBP', 'MXN', 'COP'];

const foodName = (f: string) => FOODS[f].n.toLowerCase();
const isLose = (A: Answers) => str(A.goal).startsWith('Lose');
/** Weight-loss questions apply only to people Remy may plan weight loss for (see profile/screen.ts). */
const losing = (A: Answers) => isLose(A) && !noWeightLoss(A);
const badVeg = (A: Answers) => {
  const r = allRatings(A);
  return Object.keys(r).filter((f) => FOODS[f]?.veg && (r[f] === 'dislike' || r[f] === 'never'));
};

const QUESTIONS: Omit<Question, 'i'>[] = [
  /* ---------- 1. Safety ---------- */
  { id: 'allergies', sec: 'safety', type: 'multi', none: 'None', other: true, required: true,
    say: () => 'Do you have any food allergies?',
    why: 'Allergies become hard rules. I check every recipe, sauce and substitution against them, and they stay separate from your likes and dislikes.',
    opts: [...ALLERGY_OPTS, 'None'], sample: ['Shellfish'],
    ack: (v) => (has(v, 'None') ? 'Good to know: no allergies.' : null) },
  { id: 'allergy_confirm', sec: 'safety', type: 'single', required: true,
    when: (A) => real(A.allergies).length > 0,
    because: (A) => 'Because you listed ' + listText(real(A.allergies)),
    say: (A) => 'Let me confirm: ' + listText(real(A.allergies)) + ' will be a hard rule. I won’t suggest it anywhere, including hidden sources like sauces. Is that right?',
    why: 'Many allergens hide in sauces. For shellfish, that includes oyster sauce and some fish sauces. I check ingredient aliases and what each one usually contains, but recipes and factories vary by brand, so always read labels too.',
    opts: [
      { v: 'Yes, never include it', d: 'Treat it as a hard rule everywhere' },
      // Same value as STRICT_ALLERGY in planning/rules.ts (not imported: rules.ts imports this file).
      { v: 'Yes, and skip ingredients that often carry it', d: 'Stricter: also leave out foods like buns that often have sesame. I can’t see factory lines, so still read labels' },
      { v: 'Let me change my answer', d: 'Go back to the allergy list' },
    ],
    sample: 'Yes, never include it',
    ack: (v) => (v === 'Let me change my answer' ? null : 'Locked in. That’s a hard rule now, stored apart from your preferences.') },
  { id: 'intolerances', sec: 'safety', type: 'multi', none: 'None', other: true, skip: true,
    say: () => 'Any intolerances? Foods that don’t sit well, even if they aren’t allergies.',
    why: 'I’ll avoid these by default. You can loosen them later if small amounts are fine for you.',
    opts: ['Lactose', 'Gluten', 'Beans and lentils', 'Very spicy food', 'Caffeine', 'None'], sample: ['None'] },
  { id: 'diet', sec: 'safety', type: 'multi', none: 'No restrictions', other: true, required: true,
    say: () => 'Do you follow any dietary rules, for religious, ethical or other reasons?',
    opts: ['No restrictions', 'Vegetarian', 'Vegan', 'Pescatarian', 'No pork', 'No red meat', 'Halal', 'Kosher'],
    sample: ['No restrictions'] },
  { id: 'never', sec: 'safety', type: 'chips', skip: true,
    say: () => 'Is there anything you never want me to suggest, for any reason?',
    why: 'This list is a strong preference, not an allergy. I’ll leave these out, and you can take them off the list whenever you want.',
    suggest: ['Mushrooms', 'Olives', 'Cilantro', 'Blue cheese', 'Liver', 'Anchovies', 'Coconut', 'Eggplant'],
    sample: ['Mushrooms', 'Olives', 'Cilantro'],
    ack: (v) => (arr(v).length ? listText(arr(v)) + ': off the table.' : null) },
  { id: 'health', sec: 'safety', type: 'multi', none: 'None', skip: true,
    say: () => 'Any health considerations I should keep in mind?',
    why: 'I’m not a medical professional, and Remy doesn’t give medical advice. For anything medical, a doctor or registered dietitian is the right guide. This just helps me avoid obviously poor fits.',
    opts: ['None', 'Blood sugar or diabetes', 'Blood pressure', PREGNANT, BREASTFEEDING, 'Kidney disease', 'Digestive condition', EATING_DISORDER, 'Appetite medicine, like GLP-1', 'Prefer not to say'],
    sample: ['None'],
    ack: (v) =>
      [PREGNANT, BREASTFEEDING, EATING_DISORDER].some((x) => has(v, x))
        ? REFER_NOTE
        : real(v).length && !has(v, 'Prefer not to say')
          ? 'Thanks. I’ll keep meals general. Please check the plan with your care team, since I can’t tailor it medically.'
          : null },
  { id: 'age', sec: 'safety', type: 'single', skip: true, grid: true,
    say: () => 'Which age group are you in?',
    why: 'Some guidance changes with age: teenagers are still growing, and after 65 keeping muscle matters more than the scale. A range is all I need.',
    opts: AGE_OPTS,
    sample: '18–64',
    ack: (v) =>
      v === 'Under 18'
        ? 'Thanks. Since you’re still growing, I won’t plan for weight loss. I’ll keep meals regular and balanced, and it’s worth involving a parent or doctor in any bigger changes.'
        : v === '65 or older'
          ? 'Noted. I’ll keep changes gentle, with protein at every meal.'
          : null },

  /* ---------- 2. Goals ---------- */
  { id: 'goal', sec: 'goals', type: 'single', required: true,
    say: () => 'What’s the main thing you want from Remy?',
    opts: ['Lose weight and body fat, sustainably', 'Eat more regular meals', 'Save time on cooking', 'Eat more variety', 'Keep things as they are, just organized'],
    sample: 'Lose weight and body fat, sustainably',
    ack: (v, A) => (str(v).startsWith('Lose') ? (noWeightLoss(A) ? REFER_NOTE : 'Sustainable it is. No banned foods and no extreme cuts.') : null) },
  { id: 'pace', sec: 'goals', type: 'single',
    when: losing,
    because: () => 'Because your goal is sustainable weight loss',
    say: () => 'What does “sustainable” look like for you?',
    why: 'There is no required number here. Calorie estimates are optional, and they are always estimates.',
    opts: [
      { v: 'Gentle and flexible', d: 'Small swaps and sensible portions, no counting' },
      { v: 'Some structure', d: 'Portion guidance and a balanced plate' },
      { v: 'Detailed', d: 'Show estimated calories per meal' },
    ],
    sample: 'Some structure' },
  { id: 'calories', sec: 'goals', type: 'number', skip: true,
    when: (A) => A.pace === 'Detailed' && !noWeightLoss(A),
    because: () => 'Because you asked for detailed guidance',
    say: () => 'Do you have a daily calorie estimate you’d like me to aim near?',
    why: 'Optional. If you have one from a professional or an app, I’ll use it as a rough guide. I won’t push below it or treat it as exact.',
    unit: 'kcal / day (estimate)', sample: '' },
  { id: 'structure', sec: 'goals', type: 'single', required: true,
    say: () => 'How closely do you want to follow a plan?',
    opts: [
      { v: 'Plan every meal', d: 'I like knowing exactly what I’m eating' },
      { v: 'Plan most meals', d: 'Leave room for a meal out or a change of mind' },
      { v: 'Loose ideas', d: 'Give me options and I’ll decide' },
    ],
    sample: 'Plan most meals' },
  { id: 'balance', sec: 'goals', type: 'single', skip: true,
    say: () => 'Want me to help balance your meals? I’d check for protein at each meal and some fruit or vegetables every day, using only foods you already accept.',
    why: 'Protein helps you stay full and keep muscle while losing fat. Fruit and vegetables add fiber and volume. This is general guidance, not a personal nutrition prescription.',
    opts: [
      { v: 'Yes, suggest sides', d: 'I add sides you can remove' },
      { v: 'Just show me', d: 'Flags only, no changes' },
      { v: 'No thanks' },
    ],
    sample: 'Yes, suggest sides',
    ack: (v) => (v === 'No thanks' ? 'Okay, no balance checks. You can turn them on later.' : null) },
  { id: 'progress', sec: 'goals', type: 'single', skip: true,
    when: losing,
    because: () => 'Because your goal is sustainable weight loss',
    say: () => 'How would you like to notice progress?',
    why: 'The scale jumps around from week to week. Hunger, energy and how clothes fit are often more useful signals.',
    opts: [
      { v: 'How I feel and how clothes fit' },
      { v: 'Add an optional weekly weight', d: 'Shown as a trend, never a daily number' },
      { v: 'I’d rather not track' },
    ],
    sample: 'How I feel and how clothes fit' },
  { id: 'appetite', sec: 'goals', type: 'multi', skip: true,
    say: () => 'When are you usually hungriest?',
    opts: ['Mornings', 'Midday', 'Evenings', 'Snacky afternoons', 'Late-night cravings', 'I often skip breakfast'],
    sample: ['Snacky afternoons', 'Late-night cravings'],
    ack: (v) => (has(v, 'Late-night cravings') ? 'Noted. An evening sweet slot can help with late cravings.' : null) },
  { id: 'schedule', sec: 'goals', type: 'multi', required: true,
    say: () => 'Which meals and snacks do you usually eat?',
    opts: ['Breakfast', 'Lunch', 'Afternoon snack', 'Dinner', 'Evening sweet'],
    sample: ['Breakfast', 'Lunch', 'Afternoon snack', 'Dinner', 'Evening sweet'] },
  { id: 'past', sec: 'goals', type: 'multi', other: true, skip: true,
    say: () => 'What made past meal plans hard to stick with?',
    why: 'This tells me what to avoid repeating.',
    opts: ['Food I didn’t actually like', 'Too much cooking', 'Got bored', 'Too strict, no sweets', 'Too expensive', 'Always hungry', 'Food went bad'],
    sample: ['Food I didn’t actually like', 'Too strict, no sweets', 'Too much cooking'],
    ack: (v) => {
      const s: string[] = [];
      if (has(v, 'Food I didn’t actually like')) s.push('That’s why we start with taste.');
      if (has(v, 'Too strict, no sweets')) s.push('Sweets stay in the plan from day one.');
      if (has(v, 'Too much cooking')) s.push('One prep day, and I’ll keep it efficient.');
      return s.join(' ') || null;
    } },

  /* ---------- 3. Taste ---------- */
  { id: 'cuisines', sec: 'taste', type: 'tiles', required: true,
    say: () => 'Which cuisines do you reach for?',
    opts: [
      { v: 'Italian', e: '🍝' }, { v: 'Mexican', e: '🌮' }, { v: 'American comfort', e: '🍔' }, { v: 'Japanese', e: '🍱' },
      { v: 'Chinese', e: '🥡' }, { v: 'Thai', e: '🍜' }, { v: 'Indian', e: '🍛' }, { v: 'Mediterranean', e: '🥙' },
      { v: 'Korean', e: '🍲' }, { v: 'Latin American', e: '🫓' }, { v: 'Middle Eastern', e: '🧆' }, { v: 'Breakfast foods', e: '🥞' },
    ],
    sample: ['Italian', 'Mexican', 'American comfort', 'Japanese', 'Breakfast foods'] },
  { id: 'favorites', sec: 'taste', type: 'chips', required: true,
    say: () => 'Tell me a few meals you’d happily eat any week.',
    why: 'Your real favorites are the best starting point. I’ll build versions of these that fit your goal.',
    suggest: ['Chicken tenders', 'Spaghetti with meat sauce', 'Chicken burrito bowl', 'Teriyaki chicken and rice', 'Pancakes', 'Mac and cheese', 'Cheeseburger', 'Quesadillas'],
    sample: ['Chicken tenders', 'Spaghetti with meat sauce', 'Chicken burrito bowl', 'Teriyaki chicken and rice', 'Pancakes'] },
  { id: 'flavors', sec: 'taste', type: 'multi', required: true,
    say: () => 'Which flavors do you enjoy most?',
    opts: ['Savory', 'Sweet', 'Cheesy', 'Smoky', 'Tangy', 'Garlicky', 'Herby', 'Mild', 'Spicy'],
    sample: ['Savory', 'Sweet', 'Cheesy', 'Smoky', 'Mild'] },
  { id: 'sauces', sec: 'taste', type: 'multi', other: true, skip: true,
    say: () => 'Which sauces or seasonings do you like?',
    opts: ['Marinara', 'Teriyaki', 'BBQ', 'Ranch', 'Honey mustard', 'Mild salsa', 'Pesto', 'Soy sauce', 'Alfredo', 'Ketchup', 'Hot sauce', 'Plain, no sauce'],
    sample: ['Marinara', 'Teriyaki', 'BBQ', 'Honey mustard', 'Mild salsa', 'Ranch'],
    ack: (v) => (real(v).length > 2 ? 'Good. I can build a lot from ' + listText(real(v).slice(0, 3)) + '.' : null) },
  { id: 'rateA', sec: 'taste', type: 'rate', foods: FOOD_GROUP_A, required: true,
    say: () => 'How do you feel about these staples? Tap one level for each.',
    why: '“Some ways” means you eat it only when it’s prepared a certain way. I’ll ask which ways next.',
    sample: { chicken: 'love', beef: 'like', turkey: 'okay', salmon: 'dislike', tuna: 'dislike', eggs: 'ways', tofu: 'dislike', beans: 'dislike', rice: 'love', pasta: 'love', potatoes: 'love', oats: 'like', cheese: 'love', yogurt: 'ways' } },
  { id: 'rateB', sec: 'taste', type: 'rate', foods: FOOD_GROUP_B, required: true,
    say: () => 'And these vegetables and fruits?',
    sample: { broccoli: 'ways', carrots: 'like', spinach: 'ways', peppers: 'dislike', zucchini: 'dislike', tomatoes: 'ways', onions: 'ways', mushrooms: 'never', greenbeans: 'okay', corn: 'like', avocado: 'okay', berries: 'love', bananas: 'like', apples: 'like', grapes: 'love' },
    ack: (_v, A) => {
      const l = ratedAs(A, 'love');
      return l.length ? 'I’ll build from what you love: ' + listText(l.slice(0, 4).map(foodName)) + '.' : null;
    } },
  { id: 'ways', sec: 'taste', type: 'ways', skip: true,
    when: (A) => ratedAs(A, 'ways').length > 0,
    because: (A) => 'Because you said ' + listText(ratedAs(A, 'ways').map(foodName)) + ' only work certain ways',
    say: () => 'Which preparations work for you?',
    why: 'This lets me use a food you’d otherwise avoid, in the one form you like.',
    sample: { eggs: ['Scrambled', 'Baked into something'], yogurt: ['Sweetened or flavored', 'Baked into something'], broccoli: ['Roasted until crispy', 'With cheese'], spinach: ['Blended into a sauce'], tomatoes: ['Blended into a sauce'], onions: ['Finely chopped, cooked soft', 'Blended into a sauce'] } },
  { id: 'vegwhy', sec: 'taste', type: 'multi', skip: true,
    when: (A) => badVeg(A).length >= 2,
    because: (A) => 'Because you marked ' + badVeg(A).length + ' vegetables as Dislike or Never',
    say: () => 'When a vegetable doesn’t work for you, what’s usually the problem?',
    why: 'If it’s texture, roasting or blending often fixes it. If it’s taste, I’ll lean on the ones you already like.',
    opts: ['Bitter taste', 'Texture', 'Smell', 'How it’s usually cooked', 'It’s just unfamiliar'],
    sample: ['Texture', 'Bitter taste'],
    ack: (v) => (has(v, 'Texture') ? 'Texture it is. Crispy roasting and smooth sauces are my main tools, then.' : null) },
  { id: 'breakfast', sec: 'taste', type: 'multi', skip: true,
    when: (A) => has(A.schedule, 'Breakfast'),
    say: () => 'What kind of breakfast do you like?',
    opts: ['Sweet (pancakes, oats)', 'Savory (eggs, sandwiches)', 'Grab-and-go', 'Just a drink'],
    sample: ['Sweet (pancakes, oats)', 'Grab-and-go'] },
  { id: 'snacks', sec: 'taste', type: 'multi', skip: true,
    when: (A) => has(A.schedule, 'Afternoon snack'),
    say: () => 'What makes a good snack for you?',
    opts: ['Crunchy', 'Sweet', 'Cheesy', 'Fruit', 'Protein (yogurt, jerky)'],
    sample: ['Crunchy', 'Cheesy', 'Sweet'] },
  { id: 'drinks', sec: 'taste', type: 'multi', skip: true,
    say: () => 'What do you usually drink?',
    why: 'Drinks aren’t part of the plan, but they help me understand your day.',
    opts: ['Water', 'Coffee with milk or sugar', 'Black coffee', 'Tea', 'Diet soda', 'Soda', 'Juice', 'Sparkling water'],
    sample: ['Water', 'Coffee with milk or sugar', 'Diet soda'] },

  /* ---------- 4. Picky-eating profile ---------- */
  { id: 'textures', sec: 'picky', type: 'multi', none: 'None of these', skip: true,
    say: () => 'Which textures are an immediate no for you?',
    why: 'Texture is often the real reason a food doesn’t work. Knowing this rules out dishes instead of whole ingredients.',
    opts: ['Slimy', 'Mushy', 'Stringy', 'Chewy or gristly', 'Grainy', 'Lumpy', 'Soggy', 'None of these'],
    sample: ['Slimy', 'Mushy', 'Stringy'],
    ack: (v) => (real(v).length && !has(v, 'None of these') ? 'Got it. No ' + listText(real(v).map((x) => x.toLowerCase())) + ' dishes.' : null) },
  { id: 'mixed', sec: 'picky', type: 'single', required: true,
    say: () => 'Mixed dishes or foods kept separate?',
    opts: [
      { v: 'Keep foods separate', d: 'Nothing touching, please' },
      { v: 'Some mixing is fine', d: 'Bowls and wraps are okay' },
      { v: 'Mixed dishes are great', d: 'Casseroles, stews, stir-fries' },
    ],
    sample: 'Some mixing is fine' },
  { id: 'vegcooked', sec: 'picky', type: 'single', skip: true,
    when: (A) => {
      const r = allRatings(A);
      return Object.keys(r).some((f) => FOODS[f]?.veg && ['love', 'like', 'okay', 'ways'].includes(r[f]));
    },
    say: () => 'Raw or cooked vegetables?',
    opts: ['Raw only', 'Cooked only', 'Depends on the vegetable'],
    sample: 'Cooked only' },
  { id: 'spice', sec: 'picky', type: 'single', required: true,
    say: () => 'How much heat can you handle?',
    opts: [{ v: 'None', d: 'Even black pepper is a lot' }, { v: 'Mild' }, { v: 'Medium' }, { v: 'Hot' }],
    sample: 'Mild' },
  { id: 'visible', sec: 'picky', type: 'single', skip: true,
    say: () => 'Does it matter if you can see an ingredient?',
    why: 'If hidden is fine, I can blend vegetables into sauces you already like.',
    opts: ['I need to see what I’m eating', 'Hidden is fine if I can’t taste it', 'I don’t mind either way'],
    sample: 'Hidden is fine if I can’t taste it' },
  { id: 'smells', sec: 'picky', type: 'multi', none: 'None', skip: true,
    say: () => 'Any smells that put you off a meal?',
    opts: ['Fish', 'Eggs', 'Broccoli or cabbage', 'Vinegar', 'Strong cheese', 'Heavy garlic', 'None'],
    sample: ['Fish', 'Broccoli or cabbage'] },
  { id: 'temps', sec: 'picky', type: 'multi', skip: true,
    say: () => 'Which meal temperatures work for you?',
    why: 'This decides whether cold lunches or overnight oats are on the table.',
    opts: ['Hot meals', 'Cold breakfasts', 'Cold lunches', 'Room temperature'],
    sample: ['Hot meals', 'Cold breakfasts'] },
  { id: 'retry', sec: 'picky', type: 'single', skip: true,
    when: (A) => ratedAs(A, 'dislike').length > 0,
    because: (A) => 'Because you marked ' + listText(ratedAs(A, 'dislike').slice(0, 3).map(foodName)) + ' as Dislike',
    say: () => 'Would you retry a food you dislike if it were cooked a completely different way?',
    opts: ['Yes, happily', 'Maybe, one at a time', 'No thanks'],
    sample: 'Maybe, one at a time' },
  { id: 'newfoods', sec: 'picky', type: 'single', skip: true,
    say: () => 'How adventurous should I be?',
    opts: [{ v: 'Stick to what I know' }, { v: 'One new thing a week', d: 'Small, low-risk tries' }, { v: 'Mix it up' }],
    sample: 'One new thing a week' },

  /* ---------- 5. Sweets ---------- */
  { id: 'sweets', sec: 'sweets', type: 'tiles', required: true,
    say: () => 'Which sweets do you love?',
    opts: [
      { v: 'Chocolate', e: '🍫' }, { v: 'Cookies', e: '🍪' }, { v: 'Ice cream', e: '🍨' }, { v: 'Brownies', e: '🟫' }, { v: 'Cake', e: '🍰' },
      { v: 'Candy', e: '🍬' }, { v: 'Pastries', e: '🥐' }, { v: 'Fruit desserts', e: '🍓' }, { v: 'Pudding', e: '🍮' }, { v: 'Cheesecake', e: '🧁' },
    ],
    sample: ['Chocolate', 'Cookies', 'Ice cream', 'Brownies', 'Cheesecake'] },
  { id: 'satisfy', sec: 'sweets', type: 'single', skip: true,
    when: (A) => has(A.flavors, 'Sweet') || real(A.sweets).length >= 3,
    because: () => 'Because sweets clearly matter to you',
    say: () => 'Which sweet thing feels most satisfying, like the craving is actually handled?',
    why: 'A smaller portion of the right thing beats a big portion of the wrong one.',
    opts: ['Something chocolatey', 'Something cold and creamy', 'Something warm and baked', 'Something chewy or candy-like'],
    sample: 'Something chocolatey' },
  { id: 'sweetfreq', sec: 'sweets', type: 'single', required: true,
    say: () => 'How often do you want something sweet?',
    opts: ['Every day', 'Most days', 'A few times a week', 'Now and then'],
    sample: 'Every day',
    ack: (v) => (v === 'Every day' ? 'Every day works. It’s built into the plan, not earned.' : null) },
  { id: 'portion', sec: 'sweets', type: 'single', skip: true,
    say: () => 'What portion style works best?',
    opts: [
      { v: 'Pre-portioned', d: 'Already divided, nothing to decide at night' },
      { v: 'Mini portions, more often' },
      { v: 'One normal treat, less often' },
    ],
    sample: 'Pre-portioned' },
  { id: 'sweetstyle', sec: 'sweets', type: 'single', skip: true,
    say: () => 'Lighter versions, real desserts, or a mix?',
    opts: [
      { v: 'Lighter versions', d: 'Yogurt bark, fruit-based treats' },
      { v: 'Real desserts, moderate portions', d: 'An actual brownie, a smaller square' },
      { v: 'A mix of both' },
    ],
    sample: 'A mix of both' },

  /* ---------- 6. Cooking and prep ---------- */
  { id: 'prepday', sec: 'prep', type: 'single', required: true, grid: true,
    say: () => 'Which day is your cooking day?',
    opts: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], sample: 'Sun' },
  { id: 'preptime', sec: 'prep', type: 'single', required: true,
    say: () => 'How much time do we really have on prep day?',
    why: 'I’ll fit the whole session inside this, including cleanup. If it doesn’t fit, I cut recipes instead of rushing you.',
    opts: ['1–2 hours', '2–3 hours', '3–4 hours', '4+ hours'],
    sample: '3–4 hours',
    ack: (v) => (v === '1–2 hours' ? 'Short and focused, then. I’ll cut the recipe count and keep things simple.' : null) },
  { id: 'skill', sec: 'prep', type: 'single', skip: true,
    say: () => 'How confident are you in the kitchen?',
    opts: [
      { v: 'Beginner', d: 'Keep steps very simple' },
      { v: 'Comfortable', d: 'I can follow most recipes' },
      { v: 'Confident', d: 'I can juggle a few things at once' },
    ],
    sample: 'Confident' },
  { id: 'equipment', sec: 'prep', type: 'multi', required: true,
    say: () => 'What equipment do you have?',
    opts: ['Oven', 'Stovetop', 'Air fryer', 'Microwave', 'Blender', 'Rice cooker', 'Slow cooker', 'Instant Pot', '2+ sheet pans'],
    sample: ['Oven', 'Stovetop', 'Air fryer', 'Microwave', 'Blender', '2+ sheet pans'] },
  { id: 'freezer', sec: 'prep', type: 'single', required: true,
    say: () => 'How much freezer space can Remy use?',
    why: 'Anything eaten more than 3–4 days after prep day needs the freezer to stay safe.',
    opts: [{ v: 'Tiny', d: 'A shelf or less' }, { v: 'Some space', d: 'Room for 8–10 portions' }, { v: 'Lots of space' }],
    sample: 'Some space',
    ack: (v) => (v === 'Tiny' ? 'With a small freezer, I’ll favor fridge-friendly meals and add a short mid-week top-up.' : null) },
  { id: 'fridge', sec: 'prep', type: 'single', skip: true,
    say: () => 'And the fridge?',
    opts: ['Usually crowded', 'Average', 'Plenty of room'], sample: 'Average' },
  { id: 'containers', sec: 'prep', type: 'single', skip: true,
    say: () => 'Roughly how many food containers do you have?',
    opts: ['Under 10', '10–15', '16–25', '25+'], sample: '16–25' },
  { id: 'leftovers', sec: 'prep', type: 'single', required: true,
    say: () => 'How do you feel about leftovers?',
    opts: ['Love them', 'Fine for a few days', 'Only if they don’t feel like leftovers', 'I dislike leftovers'],
    sample: 'Fine for a few days',
    ack: (v) => (v === 'Only if they don’t feel like leftovers' || v === 'I dislike leftovers' ? 'Then I’ll cook components you can recombine into different meals.' : null) },
  { id: 'components', sec: 'prep', type: 'single', skip: true,
    when: (A) => A.leftovers === 'Only if they don’t feel like leftovers' || A.leftovers === 'I dislike leftovers',
    because: () => 'Because leftovers aren’t your favorite',
    say: () => 'Would you assemble meals from prepped parts? For example, the same chicken becomes a bowl, a wrap, then a quesadilla.',
    opts: ['Yes, 5 minutes of assembly is fine', 'Only if it’s under 2 minutes', 'No, I want it ready to eat'],
    sample: 'Yes, 5 minutes of assembly is fine' },
  { id: 'repeats', sec: 'prep', type: 'single', required: true,
    say: () => 'Would you rather repeat favorites or have more variety?',
    why: 'More repeats means fewer recipes and a shorter prep day.',
    opts: [
      { v: 'Same meal up to 4 times a week', d: 'Fewest recipes' },
      { v: 'Up to 3 times', d: 'Balanced' },
      { v: 'Twice at most' },
      { v: 'Something different every day', d: 'Most variety, longest prep' },
    ],
    sample: 'Up to 3 times',
    ack: (v) => (str(v).includes('4') ? 'Repeating favorites keeps prep day short. I’ll aim for fewer recipes.' : str(v).includes('different') ? 'Variety it is. I’ll check that it still fits your prep time.' : null) },
  { id: 'reheat', sec: 'prep', type: 'multi', none: 'Nothing', skip: true,
    say: () => 'Which foods don’t reheat well for you?',
    opts: ['Pasta gets mushy', 'Rice dries out', 'Fried or crispy things', 'Fish', 'Eggs', 'Nothing'],
    sample: ['Fried or crispy things', 'Fish'],
    ack: (v) => (has(v, 'Fried or crispy things') ? 'Then crispy things get frozen raw and cooked fresh in minutes.' : null) },
  { id: 'methods', sec: 'prep', type: 'multi', skip: true,
    say: () => 'Favorite ways to cook?',
    opts: ['Sheet-pan roasting', 'Air frying', 'Stovetop', 'One-pot', 'Slow cooker', 'Grilling', 'Baking'],
    sample: ['Sheet-pan roasting', 'Air frying', 'Stovetop', 'Baking'] },
  { id: 'cleanup', sec: 'prep', type: 'single', skip: true,
    say: () => 'How much cleanup can you tolerate?',
    opts: ['As little as possible', 'Normal', 'I don’t mind'], sample: 'As little as possible' },

  /* ---------- 7. Practical ---------- */
  { id: 'household', sec: 'life', type: 'single', required: true,
    say: () => 'Who are you cooking for?',
    opts: ['Just me', 'Me + 1', '3–4 people', '5+ people'], sample: 'Just me' },
  { id: 'budget', sec: 'life', type: 'budget', skip: true,
    say: () => 'What’s your weekly grocery budget?',
    why: 'I only show cost estimates when I have enough price information. If the budget is tight, I’ll share ingredients across recipes.',
    sample: { amount: 110, currency: 'USD' },
    ack: (v) => {
      const b = asBudget(v);
      return b && b.amount && b.currency === 'USD' && b.amount < 55 ? 'Tight but doable. I’ll lean on shared ingredients and affordable staples.' : null;
    } },
  { id: 'store', sec: 'life', type: 'single', other: true, skip: true,
    say: () => 'Where do you usually shop?',
    opts: ['Big supermarket', 'Discount grocer', 'Warehouse club', 'Local market', 'Online delivery'], sample: 'Big supermarket' },
  { id: 'fromprep', sec: 'life', type: 'multi', required: true,
    when: (A) => real(A.schedule).length > 0,
    say: () => 'Which of your usual meals should come from prep day?',
    optsFn: (A) => arr(A.schedule),
    sample: ['Breakfast', 'Lunch', 'Afternoon snack', 'Dinner', 'Evening sweet'] },
  { id: 'work', sec: 'life', type: 'single', skip: true,
    say: () => 'What does your work week look like?',
    opts: ['On-site', 'Hybrid', 'Remote', 'Shift work', 'Not working right now'], sample: 'Hybrid' },
  { id: 'workmicro', sec: 'life', type: 'single', skip: true,
    when: (A) => A.work === 'On-site' || A.work === 'Hybrid',
    because: (A) => 'Because you work ' + (A.work === 'Hybrid' ? 'on-site some days' : 'on-site'),
    say: () => 'Is there a microwave where you work?',
    why: 'If not, I’ll plan lunches that taste good cold on those days.',
    opts: ['Yes', 'No', 'Sometimes, there’s a line'], sample: 'Yes' },
  { id: 'away', sec: 'life', type: 'multi', none: 'None', other: true, skip: true,
    say: () => 'Any meals you usually eat away from home?',
    opts: ['Friday dinner', 'Saturday dinner', 'Weekend brunch', 'Some work lunches', 'None'], sample: ['Friday dinner'] },
  { id: 'pantry', sec: 'life', type: 'multi', other: true, skip: true,
    say: () => 'What do you already keep in the pantry?',
    why: 'I’ll leave these off the grocery list. You can add them back anytime.',
    opts: ['Rice', 'Pasta', 'Oats', 'Flour', 'Sugar', 'Baking basics', 'Olive oil', 'Soy sauce', 'Basic spices', 'Honey', 'Cocoa powder', 'Peanut butter'],
    sample: ['Rice', 'Flour', 'Sugar', 'Baking basics', 'Olive oil', 'Soy sauce', 'Basic spices', 'Honey', 'Cocoa powder'] },

  /*
   * Asked later, one per weekly check-in (see `laterQuestion` in profile/profile.ts), not during the interview.
   * They join the profile once answered, so they show on the summary and can be edited like any answer.
   */
  { id: 'frozenveg', sec: 'life', type: 'single', skip: true,
    when: (A) => A.frozenveg !== undefined,
    say: () => 'Are frozen vegetables and fruit okay, or fresh only?',
    opts: ['Frozen is great', 'Fresh only', 'Depends on what it is'], sample: 'Frozen is great',
    ack: (v) => (v === 'Fresh only' ? 'Got it. Your grocery list will point out the frozen items so you can buy them fresh.' : 'Good to know.') },
  { id: 'brands', sec: 'life', type: 'chips', skip: true,
    when: (A) => A.brands !== undefined,
    say: () => 'Which brands of yogurt, sauce or snacks do you trust?',
    placeholder: 'Type a brand, then Add',
    ack: (v) => (arr(v).length ? 'I’ll show these on your grocery list.' : null) },
  { id: 'homedishes', sec: 'life', type: 'chips', skip: true,
    when: (A) => A.homedishes !== undefined,
    say: () => 'Any dishes from home or childhood you still love?',
    placeholder: 'Type a dish, then Add',
    suggest: ['Chicken noodle soup', 'Lasagna', 'Rice and beans', 'Pot roast', 'Empanadas', 'Fried rice'],
    ack: (v) => (arr(v).length ? 'Lovely. Remy’s AI ideas will use these as inspiration.' : null) },
];

export const Q: Question[] = QUESTIONS.map((q, i) => ({ ...q, i }));
export const QBY: Record<string, Question> = Object.fromEntries(Q.map((q) => [q.id, q]));
